/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as JinisRouteImport } from './routes/jinis'
import { Route as JinischaraRouteImport } from './routes/jinischara'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminExportRouteImport } from './routes/admin/export'
import { Route as AdminInterestRouteImport } from './routes/admin/interest'
import { Route as AdminMigrationRouteImport } from './routes/admin/migration'
import { Route as AdminSessionsRouteImport } from './routes/admin/sessions'
import { Route as JinisIndexRouteImport } from './routes/jinis/index'
import { Route as JinisNewRouteImport } from './routes/jinis/new'
import { Route as JinischaraIndexRouteImport } from './routes/jinischara/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const JinisRoute = JinisRouteImport.update({
  id: '/jinis',
  path: '/jinis',
  getParentRoute: () => rootRouteImport,
} as any)
const JinischaraRoute = JinischaraRouteImport.update({
  id: '/jinischara',
  path: '/jinischara',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInterestRoute = AdminInterestRouteImport.update({
  id: '/interest',
  path: '/interest',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMigrationRoute = AdminMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const JinisIndexRoute = JinisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JinisRoute,
} as any)
const JinisNewRoute = JinisNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => JinisRoute,
} as any)
const JinischaraIndexRoute = JinischaraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JinischaraRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/jinis': typeof JinisRouteWithChildren
  '/jinischara': typeof JinischaraRouteWithChildren
  '/signin': typeof SigninRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/interest': typeof AdminInterestRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/jinis/new': typeof JinisNewRoute
  '/admin/': typeof AdminIndexRoute
  '/jinis/': typeof JinisIndexRoute
  '/jinischara/': typeof JinischaraIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/interest': typeof AdminInterestRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/jinis/new': typeof JinisNewRoute
  '/admin': typeof AdminIndexRoute
  '/jinis': typeof JinisIndexRoute
  '/jinischara': typeof JinischaraIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/jinis': typeof JinisRouteWithChildren
  '/jinischara': typeof JinischaraRouteWithChildren
  '/signin': typeof SigninRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/interest': typeof AdminInterestRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/jinis/new': typeof JinisNewRoute
  '/admin/': typeof AdminIndexRoute
  '/jinis/': typeof JinisIndexRoute
  '/jinischara/': typeof JinischaraIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/jinis'
    | '/jinischara'
    | '/signin'
    | '/admin/export'
    | '/admin/interest'
    | '/admin/migration'
    | '/admin/sessions'
    | '/jinis/new'
    | '/admin/'
    | '/jinis/'
    | '/jinischara/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/admin/export'
    | '/admin/interest'
    | '/admin/migration'
    | '/admin/sessions'
    | '/jinis/new'
    | '/admin'
    | '/jinis'
    | '/jinischara'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/jinis'
    | '/jinischara'
    | '/signin'
    | '/admin/export'
    | '/admin/interest'
    | '/admin/migration'
    | '/admin/sessions'
    | '/jinis/new'
    | '/admin/'
    | '/jinis/'
    | '/jinischara/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  JinisRoute: typeof JinisRouteWithChildren
  JinischaraRoute: typeof JinischaraRouteWithChildren
  SigninRoute: typeof SigninRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jinis': {
      id: '/jinis'
      path: '/jinis'
      fullPath: '/jinis'
      preLoaderRoute: typeof JinisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jinischara': {
      id: '/jinischara'
      path: '/jinischara'
      fullPath: '/jinischara'
      preLoaderRoute: typeof JinischaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/interest': {
      id: '/admin/interest'
      path: '/interest'
      fullPath: '/admin/interest'
      preLoaderRoute: typeof AdminInterestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/migration': {
      id: '/admin/migration'
      path: '/migration'
      fullPath: '/admin/migration'
      preLoaderRoute: typeof AdminMigrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/jinis/': {
      id: '/jinis/'
      path: '/'
      fullPath: '/jinis/'
      preLoaderRoute: typeof JinisIndexRouteImport
      parentRoute: typeof JinisRoute
    }
    '/jinis/new': {
      id: '/jinis/new'
      path: '/new'
      fullPath: '/jinis/new'
      preLoaderRoute: typeof JinisNewRouteImport
      parentRoute: typeof JinisRoute
    }
    '/jinischara/': {
      id: '/jinischara/'
      path: '/'
      fullPath: '/jinischara/'
      preLoaderRoute: typeof JinischaraIndexRouteImport
      parentRoute: typeof JinischaraRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminExportRoute: typeof AdminExportRoute
  AdminInterestRoute: typeof AdminInterestRoute
  AdminMigrationRoute: typeof AdminMigrationRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminExportRoute: AdminExportRoute,
  AdminInterestRoute: AdminInterestRoute,
  AdminMigrationRoute: AdminMigrationRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface JinisRouteChildren {
  JinisNewRoute: typeof JinisNewRoute
  JinisIndexRoute: typeof JinisIndexRoute
}

const JinisRouteChildren: JinisRouteChildren = {
  JinisNewRoute: JinisNewRoute,
  JinisIndexRoute: JinisIndexRoute,
}

const JinisRouteWithChildren = JinisRoute._addFileChildren(JinisRouteChildren)

interface JinischaraRouteChildren {
  JinischaraIndexRoute: typeof JinischaraIndexRoute
}

const JinischaraRouteChildren: JinischaraRouteChildren = {
  JinischaraIndexRoute: JinischaraIndexRoute,
}

const JinischaraRouteWithChildren = JinischaraRoute._addFileChildren(
  JinischaraRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  JinisRoute: JinisRouteWithChildren,
  JinischaraRoute: JinischaraRouteWithChildren,
  SigninRoute: SigninRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
